# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            url: jdbc:mysql://localhost:3306/easyboot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
            username: easyboot
            password: Zmzhou.V587
            # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
            initial-size: 10
            # 最小连接池数量
            min-idle: 10
            # 可以在这个池中同时被分配的有效连接数的最大值
            max-active: 50
            # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
            max-wait: 60000
            # 有两个含义：1) Destroy线程会检测连接的间隔时间  2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
            time-between-eviction-runs-millis: 60000
            # Destory线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于 minEvictableIdleTimeMillis，则关闭当前连接
            min-evictable-idle-time-millis: 300000
            #  用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
            #  在mysql中通常为select 'x'，在oracle中通常为select 1 from dual
            validation-query: select 'x'
            # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效.
            test-while-idle: true
            # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            test-on-borrow: true
            # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            test-on-return: true
            pool-prepared-statements: true
            # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
            #  在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
            max-pool-prepared-statement-per-connection-size: 100
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            # 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
            filters: config,stat,wall,log4j2
            filter:
                log4j2:
                    enabled: true
                stat:
                  enabled: true
                  db-type: mysql
                  slow-sql-millis: 2000
                  log-slow-sql: true
                  merge-sql: true
                wall:
                  enabled: true
                  config:
                      # 不允许删除表
                      drop-table-allow: false
                      # 是否允许删除数据
                      delete-allow: true
            # 对于建立时间超过removeAbandonedTimeout的连接强制关闭
            remove-abandoned: false
            # 180秒，也就是3分钟
            remove-abandoned-timeout: 1800
            # 关闭abanded连接时输出错误日志
            log-abandoned: true
            # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
            #是否启用StatFilter默认值true
            web-stat-filter:
                enabled: true
                exclusions: .js,.gif,.jpg,.bmp,.png,.css,.ico,/druid/*
                session-stat-enable: true
                # 监控最大session数，默认是1000
                session-stat-max-count: 1000
                # 是否启用监控单个Url调用的sql列表
                profile-enable: true
                # 使druid当前session的用户是谁，session_user_key是你保存到session中的sessionName
                principalSessionName: session_user_key
                # 使druid只当当前的user是谁,cookie_user_key是你保存在cookie中的cookieName
                principalCookieName: cookie_user_key
            # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
            #是否启用StatViewServlet默认值true
            stat-view-servlet:
                enabled: true
                #      监控界面登录用户名密码
#                login-username: admin
#                login-password: Zmzhou.123
                url-pattern: /druid/*
                reset-enable: false
                # IP白名单 (和deny同时存在时，deny优先于allow) 如果满足deny的话提示:Sorry, you are not permitted to view this page
                allow: 127.0.0.1
                deny:
                # Spring监控，对内部各接口调用的监控，检查spring健康
            aop-patterns: com.github.zmzhou.easyboot.api.*.controller.*,com.github.zmzhou.easyboot.framework.web.*
    redis:
        host: 127.0.0.1
        password: Redis.127
        port: 6379
        # 连接池配置
        lettuce:
            pool:
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
                #连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池中的最小空闲连接
                min-idle: 0
        timeout: 60000ms


